### ISSUE TITLE
Add support for Currencies

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#12]
We should have a dropdown next to the price field on each property letting users choose the currency for the listing. Improving on this we should let users set a default currency in the main settings page. 

Later on this can be improved on, by possibly updating the templates to let site visitors choose a currency when viewing the listings on the site.

**Comment by davebonds** [comment]
Agreed.

**Comment by amcn84** [comment]
Just changing the currency marker won't make the data accurate. This would also need to calculate the price based on an exchange rate (that fluctuates). There are some services out their that we could hook into to get the updated price based on the currency chosen.

**Comment by davebonds** [comment]
Global setting for currency display symbol and currency code added in  ecdba7515e704f3269796ba4703de8bc485aabf8
