### ISSUE TITLE
Add Flitering for Listing CPT in WP Admin

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#25]
It would be great for us to add some improved filtering to WP Listings. Specifically dropdowns for the default taxonomies, such as property type and property status.

![Screenshot](https://www.evernote.com/shard/s1/sh/2bbf4653-5170-4dc0-8e8d-04178dafef10/c4d282b264743f9dee9498c89c711eec/res/cd4e2249-fc27-430a-9f70-b082dafc3251/skitch.png?resizeSmall&width=832)

**Comment by davebonds** [comment]
https://github.com/agentevolution/wp-listings/commit/ee4b29914f00f3fe66f20a3d7b1c732493031521
