### ISSUE TITLE
Remove all default terms for the taxonomies

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#26]
Instead of having the plugin insert default terms, we should just update the settings page to have a button that lets the user insert default terms as an option. Maybe one for full demo data as well.

**Comment by davebonds** [comment]
You can use filters to remove the default taxonomy terms for status and property type:
`wp_listings_default_status_terms` filter to add or remove default taxonomy terms
`wp_listings_default_property_type_terms` filter to add or remove default taxonomy terms
