### ISSUE TITLE
Jetpack Related Posts override bug

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#36]
A while back I added some code to override the text "Related" to "Similar Listings". There is a small bug, where for non listing pages it removes the text all together. Simply moving `return $headline;` outside of the if statement fixes the bug. 

Around line 208 in `includes/functions/php`.

**Comment by davebonds** [comment]
Fixed in f8ffd7177100dc8f208cb1dd8066084673dc7e81
