### ISSUE TITLE
Error after Update to 2.0.0

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#44]
After updating, we noticed the following error:

```php
Warning: require_once(/wp-content/plugins/wp-listings/includes/wp-api.php): failed to open stream: No such file or directory in /wp-content/plugins/wp-listings/plugin.php on line 76
```

**Comment by davebonds** [comment]
This was a temporary post commit issue only affecting the wp.org svn repository. The 2.0.0 version now available on wp.org has removed API support until the commit issue is resolved.
