### ISSUE TITLE
Terms - can I have multiple listings rotate through?

### ISSUE THREAD

**Issue by j0hnluke** [agentevolution/wp-listings#51]
I was able via shortcode to make the listing show up as multiple terms which is great.

My question is how do I make it rotate through multiple listings.

If have a limit of 3 - is there a way I can make them rotate randomly through all of the posts that are that term?

Right now my shortcode looks like this >> [listings taxonomy="status" terms="new, reduced, featured, active" limit="3" columns="3"]

I'm implementing this on bottitta.com

You can contact me on twitter as well @J0hnluke

Thanks

**Comment by davebonds** [comment]
The shortcode would need to be modified to accept an additional parameter of random.

**Comment by j0hnluke** [comment]
Has this been done before? Where I can see some code. I'm sorry I don't know php and am more of a designer than developer.
