### ISSUE TITLE
Unexpected character in input: '\' (ASCII=92) state=1 

### ISSUE THREAD

**Issue by ctbcma** [agentevolution/wp-listings#53]
Hello,

I am having issues activating the plugin. I am running a current version of PHP. This is the error code that I am getting: 
Parse error: syntax error, unexpected T_STRING in 
/wp-content/plugins/wp-listings/includes/class-listing-import.php on line 48

**Comment by amcn84** [comment]
This may be in regards to a listing you are trying to import. To further troubleshoot this can you send an email to help@idxbroker.com with your website and account ID number?
