### ISSUE TITLE
Import Properties revert to Draft Post Status

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#59]
It appears that many properties are reverting to "Draft" when the update cron `wp_listings_idx_update` runs to import/update listings. They are active listings, and this occurs even after we changed the setting to "Do Not Update". Below is a screenshot of the current import settings.
![settings](https://cloud.githubusercontent.com/assets/3837/13886850/2f4fc3fc-ecf6-11e5-8f23-77ddefbcfd36.png)

**Comment by bhubbard** [comment]
Another example: https://wordpress.org/support/topic/a-single-listing-goes-into-draft-by-itself

**Comment by davebonds** [comment]
I believe this is fixed in commit da66913261974f3fa70da44427fccc2e10d1ad4b -- Can you verify?

**Comment by bhubbard** [comment]
@davebonds It does look like this is fixed. Would it be possible to get this update pushed out soon?

**Comment by davebonds** [comment]
Excellent. We have a release with more bug fixes and updates scheduled for as early as next week.
