### ISSUE TITLE
Add Text Domain to Support WordPress Translations

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#62]
Based on this list below I think this needs to get addressed:

https://wordpress.org/support/topic/translate-to-the-brazilian-language?replies=1

https://wordpress.org/support/topic/translating-problems?replies=1

https://wordpress.org/support/topic/the-plugin-cant-be-translated-?replies=7

https://wordpress.org/support/topic/translate-112?replies=1

https://wordpress.org/support/topic/translations-archives?replies=1

https://wordpress.org/support/topic/translating-problems?replies=1

https://wordpress.org/support/topic/translation-problem-56?replies=2

https://wordpress.org/support/topic/changing-beds-baths-sq-ft-to-vietnamese-return-error?replies=1

**Comment by davebonds** [comment]
There is a text domain.. however there may be some strings where it doesn't exist. I think this is more of a user issue.

**Comment by bhubbard** [comment]
![wp-listings_plugin_php_at_master_ _agentevolution_wp-listings 2](https://cloud.githubusercontent.com/assets/3837/14050137/1fac6708-f277-11e5-9340-cd6e8ff566f2.png)

Are you sure, maybe it got removed at some point? Different Branch? Also even though you guys renamed the plugin the text domain must remain `wp-listings` to match the slug of the plugin to work with the new translation features wordpress.org offers.

**Comment by bhubbard** [comment]
Also going thru the code a bit it looks like you were using `wp_listings` as the text domain throughout, it should be replaced with `wp-listings`.

**Comment by davebonds** [comment]
Hmm.. you're right. That's odd. Will add it back in the next update and replace the underscore with a hyphen.

**Comment by davebonds** [comment]
Fixed in 7b32c863bdc353d1f4d46de6f21b00e3bc8f05f1
