### ISSUE TITLE
BUG: IDX Import

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#66]
It appears that it currently only inserts the first image of the property into the gallery section.

**Comment by davebonds** [comment]
This is by design. Only if using the Equity API component will it import all images.

**Comment by bhubbard** [comment]
Why should this only be available to Equity Theme owners? WordPress is perfectly capable of importing all the images with the IDX Broker API. 

@antonioortegajr

**Comment by antonioortegajr** [comment]
It isn't locked to theme owners. You are correct that WP or anything that can make an API call is capable. Anyone wanting to do the same would need to recreate the calls the Equity framework makes.
